
DIR=../../../F20-1015
PP=`pwd`

PY= \
	all.sql \
	ans-hw29.sql \
	ass_4_1.sql \
	city_copy.sql \
	city.sql \
	grade_hw_no.sql \
	hw01_0.setup.sql \
	hw01_1.sql \
	hw02_1.sql \
	hw02_2.sql \
	hw02_2.test01.sql \
	hw02_3.sql \
	hw03_1.sql \
	hw03_1.test01.sql \
	hw03_2.sql \
	hw03_3.sql \
	hw03_4.sql \
	hw03_5.sql \
	hw04_1.sql \
	hw04_2.sql \
	hw04_2.test01.sql \
	hw04_3.sql \
	hw05_0.sql \
	hw05_0.test01.sql \
	hw05_1.sql \
	hw05_2.sql \
	hw06_1.sql \
	hw06_1.test01.sql \
	hw06_2.sql \
	hw06_3.sql \
	hw06_4.sql \
	hw08_1.sql \
	hw08_2.sql \
	hw08_3.sql \
	hw08_4.sql \
	hw09_1.sql \
	hw09_2.sql \
	hw09_3.sql \
	hw09_4.sql \
	hw10_1.sql \
	hw11_1.sql \
	hw11_2.sql \
	hw11_3.sql \
	hw12_1.sql \
	hw12_2.sql \
	hw12_3.sql \
	hw12_4.sql \
	hw13_1.sql \
	hw13_2.sql \
	hw13_3.sql \
	hw13_4.sql \
	hw14_1.sql \
	hw14_2.sql \
	hw15_1.sql \
	hw15_2.sql \
	hw16_1.sql \
	hw17_1.sql \
	hw17_2.sql \
	hw17_3.sql \
	hw17_4.sql \
	hw17_5.sql \
	hw17_6.sql \
	hw18_1.sql \
	hw18_2.sql \
	hw19_1.sql \
	hw20_1.sql \
	hw20_2.sql \
	hw21_1.sql \
	hw22_1.sql \
	hw22_2.sql \
	hw23_1.sql \
	hw24_1.sql \
	hw25_1.sql \
	hw25_2.sql \
	hw26_01.sql \
	hw26_02.sql \
	hw26_03.sql \
	hw26_04.sql \
	hw26_05.sql \
	hw26_06.sql \
	hw26_07.sql \
	hw26_08.sql \
	hw26_09.sql \
	hw26_10.sql \
	hw26_11.sql \
	hw26_14.sql \
	hw28_1.sql \
	hw29_1.sql \
	hw29_2.sql \
	hw31_1.sql \
	hw31_2.sql \
	hw31_4.sql \
	hw32_1.sql \
	hw32_2.sql \
	hw32_3.sql \
	hw32_5.sql \
	hw33_1.sql \
	hw33_2.sql \
	hw34_18.sql \
	hw35_1.sql \
	hw35_2.sql \
	hw36_3.sql \
	hw36_4.sql \
	hw37_1.sql \
	hw37_2.sql \
	hw37_3.sql \
	hw37_4.sql \
	hw37_5.sql \
	hw38_01.sql \
	hw38_02.sql \
	hw38_03.sql \
	hw38_04.sql \
	hw38_05.sql \
	hw38_06.sql \
	hw38_07.sql \
	hw38_08.sql \
	hw38_09.sql \
	hw38_10.sql \
	hw38_11.sql \
	hw38_12.sql \
	hw39_1.sql \
	hw39_2.sql \
	hw39_3.sql \
	hw40_1.sql \
	hw41_01.sql \
	hw42_01.sql \
	hw42_02.sql \
	hw42_04.sql \
	hw43_1.sql \
	hw43_2.sql \
	hw43_3.sql \
	hw44_1.sql \
	hw44_2.sql \
	hw45_1.sql \
	hw46_1.sql \
	hw46_2.sql \
	hw46_3.sql \
	hw46_4.sql \
	hw46_5.sql \
	hw46_6.sql \
	hw47_1.sql \
	hw47_2.sql \
	hw48_1.sql \
	hw48_2.sql \
	hw49_1.sql \
	hw50_1.sql \
	old1.sql \
	s1.sql \
	s2.sql \
	s3.sql \
	test-select.sql
#endPY

IMG= \
	PostgreSQL-Full-Outer-Join.png \
	PostgreSQL-Full-Outer-Unique-Join.png \
	PostgreSQL-Inner-Join.png \
	PostgreSQL-Left-Outer-Join.png
#endIMG

HTML= \
	hw01.html \
	hw02.html \
	hw03.html \
	hw04.html \
	hw05.html \
	hw06.html \
	hw07.html \
	hw08.html \
	hw09.html \
	hw10.html \
	hw11.html \
	hw12.html \
	hw13.html \
	hw14.html \
	hw15.html \
	hw16.html \
	hw17.html \
	hw18.html \
	hw19.html \
	hw20.html \
	hw21.html \
	hw22.html \
	hw23.html \
	hw24.html \
	hw25.html \
	hw26.html \
	hw27.html \
	hw28.html \
	hw29.html \
	hw30.html \
	hw31.html \
	hw32.html \
	hw33.html \
	hw34.html \
	hw35.html \
	hw36.html \
	hw37.html \
	hw38.html \
	hw39.html \
	hw40.html \
	hw41.html \
	hw42.html \
	hw43.html \
	hw44.html \
	hw45.html \
	hw46.html \
	hw47.html \
	hw48.html \
	hw49.html \
	hw50.html
#endHTML

MD= \
	hw01.md \
	hw02.md \
	hw03.md \
	hw04.md \
	hw05.md \
	hw06.md \
	hw07.md \
	hw08.md \
	hw09.md \
	hw10.md \
	hw11.md \
	hw12.md \
	hw13.md \
	hw14.md \
	hw15.md \
	hw16.md \
	hw17.md \
	hw18.md \
	hw19.md \
	hw20.md \
	hw21.md \
	hw22.md \
	hw23.md \
	hw24.md \
	hw25.md \
	hw26.md \
	hw27.md \
	hw28.md \
	hw29.md \
	hw30.md \
	hw31.md \
	hw32.md \
	hw33.md \
	hw34.md \
	hw35.md \
	hw36.md \
	hw37.md \
	hw38.md \
	hw39.md \
	hw40.md \
	hw41.md \
	hw42.md \
	hw43.md \
	hw44.md \
	hw45.md \
	hw46.md \
	hw47.md \
	hw48.md \
	hw49.md \
	hw50.md
#endMD

RAW_MD= \
	hw01.raw.md \
	hw02.raw.md \
	hw03.raw.md \
	hw04.raw.md \
	hw05.raw.md \
	hw06.raw.md \
	hw07.raw.md \
	hw08.raw.md \
	hw09.raw.md \
	hw10.raw.md \
	hw11.raw.md \
	hw12.raw.md \
	hw13.raw.md \
	hw14.raw.md \
	hw15.raw.md \
	hw16.raw.md \
	hw17.raw.md \
	hw18.raw.md \
	hw19.raw.md \
	hw20.raw.md \
	hw21.raw.md \
	hw22.raw.md \
	hw23.raw.md \
	hw24.raw.md \
	hw25.raw.md \
	hw26.raw.md \
	hw27.raw.md \
	hw28.raw.md \
	hw29.raw.md \
	hw30.raw.md \
	hw31.raw.md \
	hw32.raw.md \
	hw33.raw.md \
	hw34.raw.md \
	hw35.raw.md \
	hw36.raw.md \
	hw37.raw.md \
	hw38.raw.md \
	hw39.raw.md \
	hw40.raw.md \
	hw41.raw.md \
	hw42.raw.md \
	hw43.raw.md \
	hw44.raw.md \
	hw45.raw.md \
	hw46.raw.md \
	hw47.raw.md \
	hw48.raw.md \
	hw49.raw.md \
	hw50.raw.md
#endRAW_MD

all: pre $(MD) $(HTML) gen_data.sql syllabus.html

runM4Markdown_to_HTML:
	m4 -P tmp.raw.md | ./add-space.sh >tmp.md
	blackfriday-tool ./tmp.md tmp.html
	@echo "PASS"
.PHONEY: runM4Markdown_to_HTML


pre:
	cp /dev/null open.1
.PHONEY: pre

#gen_data.sql: $(RAW_MD) Makefile get-tags.go
#	go run get-tags.go $(RAW_MD) >gen_data.sql
gen_data.sql: $(RAW_MD) Makefile get-tags.go $(PY)
	go run get-tags.go $(RAW_MD) >gen_data.sql


%.md: %.raw.md $(PY) $(IMG)
	m4 -P $< >$@

%.html: %.md
	blackfriday-tool ./$< $@
	echo cat ./${DIR}/md.css $@ >/tmp/$@
	cat ./${DIR}/css/pre ./${DIR}/css/markdown.css ./${DIR}/css/post ./${DIR}/md.css ./${DIR}/css/hpre $@ ./${DIR}/css/hpost >/tmp/$@
	mv /tmp/$@ ./$@
	echo "file://${PP}/$@" >>open.1

run_all:
	psql -a <all.sql >all.out

make: m1 m2 m3 m4
.PHONEY: make m1 m2 m3 m4

m1:
	rm -f ,*.sql gen_data.sql
	ls *.sql >,a
	ed ,a <ed.make0.ed
	ed Makefile <ed.make2.ed

m2:
	ls hw*.md | grep raw >,a
	ed ,a <ed.make1.ed
	ed Makefile <ed.make3.ed

m3:
	ls hw*.md | grep raw >,a
	ed ,a <ed.make5.ed
	ed Makefile <ed.make4.ed

m4:
	ls hw*.raw.md >,a
	ed ,a <ed.make7.ed
	ed Makefile <ed.make6.ed

gitupdate:
	git add -A .
	git commit -m "New Lessons"
	git push

