-- https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States
-- https://www.usatoday.com/story/money/2019/08/01/economic-growth-by-state-gdp-fastest-growing-shrinking-economies/39822123/

UPDATE us_state set area_rank =  1, fed_area =  1, area_sq_mi = 570641 where state_name = 'Alaska';
UPDATE us_state set area_rank =  2, fed_area =  1, area_sq_mi = 261914 where state_name = 'Texas';
UPDATE us_state set area_rank =  3, fed_area = 12, area_sq_mi = 155973 where state_name = 'California';
UPDATE us_state set area_rank =  4, fed_area =  1, area_sq_mi = 145556 where state_name = 'Montana';
UPDATE us_state set area_rank =  5, fed_area =  1, area_sq_mi = 121365 where state_name = 'New Mexico';
UPDATE us_state set area_rank =  6, fed_area = 12, area_sq_mi = 113642 where state_name = 'Arizona';
UPDATE us_state set area_rank =  7, fed_area = 12, area_sq_mi = 109806 where state_name = 'Nevada';
UPDATE us_state set area_rank =  8, fed_area =  1, area_sq_mi = 103730 where state_name = 'Colorado';
UPDATE us_state set area_rank =  9, fed_area =  1, area_sq_mi = 97105 where state_name = 'Wyoming';
UPDATE us_state set area_rank = 10, fed_area = 12, area_sq_mi = 96003 where state_name = 'Oregon';
UPDATE us_state set area_rank = 11, fed_area = 12, area_sq_mi = 82751 where state_name = 'Idaho';
UPDATE us_state set area_rank = 12, fed_area = 12, area_sq_mi = 82168 where state_name = 'Utah';
UPDATE us_state set area_rank = 13, fed_area =  1, area_sq_mi = 81823 where state_name = 'Kansas';
UPDATE us_state set area_rank = 14, fed_area =  1, area_sq_mi = 79617 where state_name = 'Minnesota';
UPDATE us_state set area_rank = 15, fed_area =  1, area_sq_mi = 76878 where state_name = 'Nebraska';
UPDATE us_state set area_rank = 16, fed_area =  1, area_sq_mi = 75898 where state_name = 'South Dakota';
UPDATE us_state set area_rank = 17, fed_area =  1, area_sq_mi = 68994 where state_name = 'North Dakota';
UPDATE us_state set area_rank = 18, fed_area =  1, area_sq_mi = 68898 where state_name = 'Missouri';
UPDATE us_state set area_rank = 19, fed_area =  1, area_sq_mi = 68679 where state_name = 'Oklahoma';
UPDATE us_state set area_rank = 20, fed_area = 12, area_sq_mi = 66582 where state_name = 'Washington';
UPDATE us_state set area_rank = 21, fed_area =  1, area_sq_mi = 57919 where state_name = 'Georgia';
UPDATE us_state set area_rank = 22, fed_area =  1, area_sq_mi = 56539 where state_name = 'Michigan';
UPDATE us_state set area_rank = 23, fed_area =  1, area_sq_mi = 55875 where state_name = 'Iowa';
UPDATE us_state set area_rank = 24, fed_area =  1, area_sq_mi = 55593 where state_name = 'Illinois';
UPDATE us_state set area_rank = 25, fed_area =  1, area_sq_mi = 54314 where state_name = 'Wisconsin';
UPDATE us_state set area_rank = 26, fed_area =  1, area_sq_mi = 53997 where state_name = 'Florida';
UPDATE us_state set area_rank = 27, fed_area =  1, area_sq_mi = 52075 where state_name = 'Arkansas';
UPDATE us_state set area_rank = 28, fed_area =  1, area_sq_mi = 50750 where state_name = 'Alabama';
UPDATE us_state set area_rank = 29, fed_area =  1, area_sq_mi = 48718 where state_name = 'North Carolina';
UPDATE us_state set area_rank = 30, fed_area =  1, area_sq_mi = 47224 where state_name = 'New York';
UPDATE us_state set area_rank = 31, fed_area =  1, area_sq_mi = 46914 where state_name = 'Mississippi';
UPDATE us_state set area_rank = 32, fed_area =  1, area_sq_mi = 44820 where state_name = 'Pennsylvania';
UPDATE us_state set area_rank = 33, fed_area =  1, area_sq_mi = 43566 where state_name = 'Louisiana';
UPDATE us_state set area_rank = 34, fed_area =  1, area_sq_mi = 41220 where state_name = 'Tennessee';
UPDATE us_state set area_rank = 35, fed_area =  1, area_sq_mi = 40953 where state_name = 'Ohio';
UPDATE us_state set area_rank = 36, fed_area =  1, area_sq_mi = 39732 where state_name = 'Kentucky';
UPDATE us_state set area_rank = 37, fed_area =  1, area_sq_mi = 39598 where state_name = 'Virginia';
UPDATE us_state set area_rank = 38, fed_area =  1, area_sq_mi = 35870 where state_name = 'Indiana';
UPDATE us_state set area_rank = 39, fed_area =  1, area_sq_mi = 30865 where state_name = 'Maine';
UPDATE us_state set area_rank = 40, fed_area =  1, area_sq_mi = 30111 where state_name = 'South Carolina';
UPDATE us_state set area_rank = 41, fed_area =  1, area_sq_mi = 24087 where state_name = 'West Virginia';
UPDATE us_state set area_rank = 42, fed_area =  1, area_sq_mi = 9775 where state_name = 'Maryland';
UPDATE us_state set area_rank = 43, fed_area =  1, area_sq_mi = 9249 where state_name = 'Vermont';
UPDATE us_state set area_rank = 44, fed_area =  1, area_sq_mi = 8969 where state_name = 'New Hampshire';
UPDATE us_state set area_rank = 45, fed_area =  1, area_sq_mi = 7838 where state_name = 'Massachusetts';
UPDATE us_state set area_rank = 46, fed_area =  1, area_sq_mi = 7419 where state_name = 'New Jersey';
UPDATE us_state set area_rank = 47, fed_area =  1, area_sq_mi = 6423 where state_name = 'Hawaii';
UPDATE us_state set area_rank = 48, fed_area =  1, area_sq_mi = 4845 where state_name = 'Connecticut';
UPDATE us_state set area_rank = 49, fed_area =  1, area_sq_mi = 3515 where state_name = 'Puerto Rico';
UPDATE us_state set area_rank = 50, fed_area =  1, area_sq_mi = 1955 where state_name = 'Delaware';
UPDATE us_state set area_rank = 51, fed_area =  1, area_sq_mi = 1034 where state_name = 'Rhode Island';
UPDATE us_state set area_rank = 52, fed_area =  1, area_sq_mi = 137 where state_name = 'District of Columbia';
UPDATE us_state set area_rank = 53, fed_area =  1, area_sq_mi = 68 where state_name = 'Virgin Islands';
